import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Every cross-page link is a plain <a> on purpose (spec §4.1, §8.7): the
    // marketing pages and the legacy pages live under different root layouts,
    // so navigation between them is always a full document load.
    rules: { "@next/next/no-html-link-for-pages": "off" },
  },
  {
    // Legacy pages are moved byte-for-byte (spec §2.2) and keep their
    // pre-existing findings (3 errors + 1 warning at the move); only these
    // rules are relaxed, and only for the legacy files.
    files: [
      "src/app/(legacy)/**",
      "src/hooks/useClientTranslation.ts",
      "src/components/ClientProvider.tsx",
      "src/lib/i18n.ts",
    ],
    rules: {
      "react/no-unescaped-entities": "off",
      "react-hooks/set-state-in-effect": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "node_modules/**",
    "next-env.d.ts",
    "assets-src/**",
    "public/**",
    "test-results/**",
    "playwright-report/**",
    // generated by scripts/build-icons.mjs
    "src/components/site/icons/paths.ts",
  ]),
]);
