// GENERATED by scripts/split-dictionaries.mjs. Do not edit by hand.
// Copy lives in ./ja/*.json and ./en/*.json (one file per owning package, spec §11).
import jaMeta from './ja/meta.json';
import jaCommon from './ja/common.json';
import jaA11y from './ja/a11y.json';
import jaHeader from './ja/header.json';
import jaStickyBar from './ja/stickyBar.json';
import jaQrDock from './ja/qrDock.json';
import jaFooter from './ja/footer.json';
import jaPersonas from './ja/personas.json';
import jaHomeHero from './ja/home.hero.json';
import jaHomeCast from './ja/home.cast.json';
import jaHomeAbout from './ja/home.about.json';
import jaHomeCall from './ja/home.call.json';
import jaHomeDemo from './ja/home.demo.json';
import jaHomeCheckpoint from './ja/home.checkpoint.json';
import jaHomeMorning from './ja/home.morning.json';
import jaHomeChat from './ja/home.chat.json';
import jaHomeLive from './ja/home.live.json';
import jaHomeGrow from './ja/home.grow.json';
import jaHomeMore from './ja/home.more.json';
import jaHomeHow from './ja/home.how.json';
import jaHomeFaq from './ja/home.faq.json';
import jaHomeCreatorsBand from './ja/home.creatorsBand.json';
import jaHomeFinal from './ja/home.final.json';
import jaCreators from './ja/creators.json';
import jaMockFan from './ja/mock.fan.json';
import jaMockStudio from './ja/mock.studio.json';
import enMeta from './en/meta.json';
import enCommon from './en/common.json';
import enA11y from './en/a11y.json';
import enHeader from './en/header.json';
import enStickyBar from './en/stickyBar.json';
import enQrDock from './en/qrDock.json';
import enFooter from './en/footer.json';
import enPersonas from './en/personas.json';
import enHomeHero from './en/home.hero.json';
import enHomeCast from './en/home.cast.json';
import enHomeAbout from './en/home.about.json';
import enHomeCall from './en/home.call.json';
import enHomeDemo from './en/home.demo.json';
import enHomeCheckpoint from './en/home.checkpoint.json';
import enHomeMorning from './en/home.morning.json';
import enHomeChat from './en/home.chat.json';
import enHomeLive from './en/home.live.json';
import enHomeGrow from './en/home.grow.json';
import enHomeMore from './en/home.more.json';
import enHomeHow from './en/home.how.json';
import enHomeFaq from './en/home.faq.json';
import enHomeCreatorsBand from './en/home.creatorsBand.json';
import enHomeFinal from './en/home.final.json';
import enCreators from './en/creators.json';
import enMockFan from './en/mock.fan.json';
import enMockStudio from './en/mock.studio.json';

export const ja = {
  meta: jaMeta,
  common: jaCommon,
  a11y: jaA11y,
  header: jaHeader,
  stickyBar: jaStickyBar,
  qrDock: jaQrDock,
  footer: jaFooter,
  personas: jaPersonas,
  home: {
    hero: jaHomeHero,
    cast: jaHomeCast,
    about: jaHomeAbout,
    call: jaHomeCall,
    demo: jaHomeDemo,
    checkpoint: jaHomeCheckpoint,
    morning: jaHomeMorning,
    chat: jaHomeChat,
    live: jaHomeLive,
    grow: jaHomeGrow,
    more: jaHomeMore,
    how: jaHomeHow,
    faq: jaHomeFaq,
    creatorsBand: jaHomeCreatorsBand,
    final: jaHomeFinal,
  },
  creators: jaCreators,
  mock: {
    fan: jaMockFan,
    studio: jaMockStudio,
  },
};

/** The full dictionary shape. Japanese is the reference locale. */
export type Dictionary = typeof ja;

const enSource = {
  meta: enMeta,
  common: enCommon,
  a11y: enA11y,
  header: enHeader,
  stickyBar: enStickyBar,
  qrDock: enQrDock,
  footer: enFooter,
  personas: enPersonas,
  home: {
    hero: enHomeHero,
    cast: enHomeCast,
    about: enHomeAbout,
    call: enHomeCall,
    demo: enHomeDemo,
    checkpoint: enHomeCheckpoint,
    morning: enHomeMorning,
    chat: enHomeChat,
    live: enHomeLive,
    grow: enHomeGrow,
    more: enHomeMore,
    how: enHomeHow,
    faq: enHomeFaq,
    creatorsBand: enHomeCreatorsBand,
    final: enHomeFinal,
  },
  creators: enCreators,
  mock: {
    fan: enMockFan,
    studio: enMockStudio,
  },
};

// Compile-time key parity: en must match ja exactly (no missing, no extra keys).
type Same<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
const parity: Same<typeof enSource, Dictionary> = true;
void parity;

export const en: Dictionary = enSource;
