#!/usr/bin/env node
// Generates src/components/site/icons/paths.ts from Material Symbols Outlined
// (weight 400, Apache-2.0): `o` = FILL 0, `f` = FILL 1, viewBox "0 -960 960 960".
//
// Source order per icon: @material-symbols/svg-400/outlined/<file>.svg, then
// assets-src/icons/<name>.svg (official glyphs the npm package no longer ships
// under that name, fetched once from fonts.gstatic.com).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PKG = join(ROOT, 'node_modules/@material-symbols/svg-400/outlined');
const VENDORED = join(ROOT, 'assets-src/icons');
const OUT = join(ROOT, 'src/components/site/icons/paths.ts');

/** Every icon the spec names (§4–§7). Add here, then run `npm run icons`. */
const ICONS = [
  'account_balance', 'add', 'alarm', 'alarm_on', 'android', 'arrow_back', 'arrow_forward',
  'auto_awesome', 'badge', 'bar_chart', 'bedtime', 'block', 'blur_on', 'calendar_month', 'call',
  'call_end', 'celebration', 'chat_bubble', 'check', 'check_circle', 'chevron_right', 'close',
  'confirmation_number', 'content_copy', 'crisis_alert', 'delete', 'do_not_disturb_on', 'download',
  'edit', 'edit_note', 'expand_less', 'expand_more', 'favorite', 'flag', 'forum', 'gavel',
  'graphic_eq', 'group', 'groups', 'home', 'hourglass_top', 'info', 'key', 'link',
  'local_fire_department', 'lock', 'mail', 'menu', 'mic', 'more_vert', 'music_note', 'nights_stay',
  'notifications', 'notifications_active', 'paid', 'pause', 'payments', 'person', 'phone_iphone',
  'photo_library', 'play_arrow', 'play_circle', 'podcasts', 'psychiatry', 'psychology', 'qr_code_2',
  'radio', 'redeem', 'replay', 'search', 'send', 'star', 'timer', 'verified', 'verified_user',
  'visibility', 'volume_up', 'workspace_premium',
];

/** Spec names whose glyph ships under a newer name in the package (same codepoint). */
const ALIASES = { phone_iphone: 'mobile_3', nights_stay: 'partly_cloudy_night' };

/** The LIVE glyph is podcasts/radio/graphic_eq only (spec §1.3, §7.0). */
const BANNED = new Set(['videocam']);

function pathOf(file) {
  const svg = readFileSync(file, 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length !== 1) throw new Error(`${file}: expected exactly one <path>, found ${paths.length}`);
  if (!/viewBox="0 -960 960 960"/.test(svg)) throw new Error(`${file}: unexpected viewBox`);
  return paths[0];
}

function resolve(name, filled) {
  const suffix = filled ? '-fill' : '';
  const candidates = [join(PKG, `${ALIASES[name] ?? name}${suffix}.svg`), join(VENDORED, `${name}${suffix}.svg`)];
  const hit = candidates.find((f) => existsSync(f));
  if (!hit) throw new Error(`icon "${name}"${filled ? ' (filled)' : ''} not found in:\n  ${candidates.join('\n  ')}`);
  return pathOf(hit);
}

const names = [...new Set(ICONS)].sort();
for (const n of names) if (BANNED.has(n)) throw new Error(`icon "${n}" is banned by the spec`);

const entries = names.map((n) => `  ${n}: {\n    o: '${resolve(n, false)}',\n    f: '${resolve(n, true)}',\n  },`);

const out = `// GENERATED by scripts/build-icons.mjs from @material-symbols/svg-400 (Apache-2.0). Do not edit.
// viewBox "0 -960 960 960"; o = outlined (FILL 0), f = filled (FILL 1).

export const PATHS = {
${entries.join('\n')}
} as const satisfies Record<string, { o: string; f: string }>;

export type IconName = keyof typeof PATHS;
`;
writeFileSync(OUT, out);
console.log(`icons: ${names.length} glyphs → ${OUT.slice(ROOT.length + 1)} (${(Buffer.byteLength(out) / 1024).toFixed(1)} KB)`);
